FROM node:20-bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive \
    NODE_ENV=development \
    npm_config_update_notifier=false \
    npm_config_fund=false

RUN apt-get update \
  && apt-get install -y --no-install-recommends docker.io ca-certificates git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

CMD ["npm", "run", "worker"]
